version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

groups:
  xunit:
    patterns:
    - "xunit*"
  spectre:
    patterns:
    - "Spectre*"
