//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lolcat.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lolcat.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [38;2;3;170;210;1mA[0m[38;2;2;174;206;1mn[0m[38;2;1;178;203;1ms[0m[38;2;1;182;199;1mi[0m[38;2;1;186;196;1mR[0m[38;2;1;190;192;1ma[0m[38;2;1;193;189;1mi[0m[38;2;1;197;185;1mn[0m[38;2;1;200;181;1mb[0m[38;2;1;204;177;1mo[0m[38;2;2;207;173;1mw[0m.
        /// </summary>
        internal static string AnsiRainbowEscaped {
            get {
                return ResourceManager.GetString("AnsiRainbowEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnsiRainbow.
        /// </summary>
        internal static string AnsiRainbowText {
            get {
                return ResourceManager.GetString("AnsiRainbowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(3,170,210)]S[/][rgb(2,174,206)]p[/][rgb(1,178,203)]e[/][rgb(1,182,199)]c[/][rgb(1,186,196)]t[/][rgb(1,190,192)]r[/][rgb(1,193,189)]e[/][rgb(1,197,185)]R[/][rgb(1,200,181)]a[/][rgb(1,204,177)]i[/][rgb(2,207,173)]n[/][rgb(3,210,169)]b[/][rgb(4,214,165)]o[/][rgb(5,217,161)]w[/].
        /// </summary>
        internal static string SpectreRainbowEscaped {
            get {
                return ResourceManager.GetString("SpectreRainbowEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectreRainbow.
        /// </summary>
        internal static string SpectreRainbowText {
            get {
                return ResourceManager.GetString("SpectreRainbowText", resourceCulture);
            }
        }
    }
}
