//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lolcat.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lolcat.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [38;2;254;68;60;1mA[0m[38;2;254;64;64;1mn[0m[38;2;254;61;67;1ms[0m[38;2;254;57;71;1mi[0m[38;2;254;54;75;1mR[0m[38;2;253;50;79;1ma[0m[38;2;253;47;83;1mi[0m[38;2;252;44;87;1mn[0m[38;2;251;41;91;1mb[0m[38;2;250;38;95;1mo[0m[38;2;249;35;99;1mw[0m.
        /// </summary>
        internal static string AnsiMarkup {
            get {
                return ResourceManager.GetString("AnsiMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnsiRainbow.
        /// </summary>
        internal static string AnsiText {
            get {
                return ResourceManager.GetString("AnsiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]🌈[/][rgb(254,61,67)]🦄[/].
        /// </summary>
        internal static string EmojiMarkup {
            get {
                return ResourceManager.GetString("EmojiMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈🦄.
        /// </summary>
        internal static string EmojiText {
            get {
                return ResourceManager.GetString("EmojiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]S[/][rgb(254,64,64)]p[/][rgb(254,61,67)]e[/][rgb(254,57,71)]c[/][rgb(254,54,75)]t[/][rgb(253,50,79)]r[/][rgb(253,47,83)]e[/][rgb(252,44,87)]R[/][rgb(251,41,91)]a[/][rgb(250,38,95)]i[/][rgb(249,35,99)]n[/][rgb(248,32,103)]b[/][rgb(246,29,107)]o[/][rgb(245,26,111)]w[/].
        /// </summary>
        internal static string SpectreMarkup {
            get {
                return ResourceManager.GetString("SpectreMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectreRainbow.
        /// </summary>
        internal static string SpectreText {
            get {
                return ResourceManager.GetString("SpectreText", resourceCulture);
            }
        }
    }
}
