//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lolcat.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lolcat.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [38;2;254;68;60;1mA[0m[38;2;254;64;64;1mn[0m[38;2;254;61;67;1ms[0m[38;2;254;57;71;1mi[0m[38;2;254;54;75;1mR[0m[38;2;253;50;79;1ma[0m[38;2;253;47;83;1mi[0m[38;2;252;44;87;1mn[0m[38;2;251;41;91;1mb[0m[38;2;250;38;95;1mo[0m[38;2;249;35;99;1mw[0m.
        /// </summary>
        internal static string AnsiMarkup {
            get {
                return ResourceManager.GetString("AnsiMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnsiRainbow.
        /// </summary>
        internal static string AnsiText {
            get {
                return ResourceManager.GetString("AnsiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]🌈[/][rgb(254,61,67)] [/][rgb(254,57,71)]l[/][rgb(254,54,75)]o[/][rgb(253,50,79)]l[/][rgb(253,47,83)]c[/][rgb(252,44,87)]a[/][rgb(251,41,91)]t[/][rgb(250,38,95)] [/][rgb(249,35,99)]🦄[/]
        ///
        ///[rgb(254,61,67)]✨[/][rgb(254,57,71)]🎉[/][rgb(253,50,79)]🎊[/][rgb(252,44,87)]🐱[/][rgb(250,38,95)]‍[/][rgb(249,35,99)]🏍[/].
        /// </summary>
        internal static string EmojiMultilineMarkup {
            get {
                return ResourceManager.GetString("EmojiMultilineMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]🌈[/]
        ///
        ///[rgb(254,61,67)]✨[/].
        /// </summary>
        internal static string EmojiMultilineMarkupWidth1 {
            get {
                return ResourceManager.GetString("EmojiMultilineMarkupWidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈 lolcat 🦄
        ///
        ///✨🎉🎊🐱‍🏍.
        /// </summary>
        internal static string EmojiMultilineText {
            get {
                return ResourceManager.GetString("EmojiMultilineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someday we&apos;ll find it, the rainbow connection
        ///The lovers, the dreamers and me
        ///
        ///🌈 lolcat 🦄.
        /// </summary>
        internal static string SpectreFrameText {
            get {
                return ResourceManager.GetString("SpectreFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]S[/][rgb(254,64,64)]p[/][rgb(254,61,67)]e[/][rgb(254,57,71)]c[/][rgb(254,54,75)]t[/][rgb(253,50,79)]r[/][rgb(253,47,83)]e[/][rgb(252,44,87)]R[/][rgb(251,41,91)]a[/][rgb(250,38,95)]i[/][rgb(249,35,99)]n[/][rgb(248,32,103)]b[/][rgb(246,29,107)]o[/][rgb(245,26,111)]w[/].
        /// </summary>
        internal static string SpectreMarkup {
            get {
                return ResourceManager.GetString("SpectreMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)]S[/][rgb(254,64,64)]o[/][rgb(254,61,67)]m[/][rgb(254,57,71)]e[/][rgb(254,54,75)]d[/][rgb(253,50,79)]a[/][rgb(253,47,83)]y[/][rgb(252,44,87)] [/][rgb(251,41,91)]w[/][rgb(250,38,95)]e[/][rgb(249,35,99)]&apos;[/][rgb(248,32,103)]l[/][rgb(246,29,107)]l[/][rgb(245,26,111)] [/][rgb(243,24,116)]f[/][rgb(241,22,120)]i[/][rgb(239,19,124)]n[/][rgb(237,17,128)]d[/][rgb(235,15,132)] [/][rgb(233,13,137)]i[/][rgb(230,11,141)]t[/][rgb(228,10,145)],[/][rgb(225,8,149)] [/][rgb(222,7,153)]t[/][rgb(219,6,158)]h[/][ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpectreMarkupSeed1 {
            get {
                return ResourceManager.GetString("SpectreMarkupSeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,57,71)]S[/][rgb(254,54,75)]o[/][rgb(253,50,79)]m[/][rgb(253,47,83)]e[/][rgb(252,44,87)]d[/][rgb(251,41,91)]a[/][rgb(250,38,95)]y[/][rgb(249,35,99)] [/][rgb(248,32,103)]w[/][rgb(246,29,107)]e[/][rgb(245,26,111)]&apos;[/][rgb(243,24,116)]l[/][rgb(241,22,120)]l[/][rgb(239,19,124)] [/][rgb(237,17,128)]f[/][rgb(235,15,132)]i[/][rgb(233,13,137)]n[/][rgb(230,11,141)]d[/][rgb(228,10,145)] [/][rgb(225,8,149)]i[/][rgb(222,7,153)]t[/][rgb(219,6,158)],[/][rgb(216,4,162)] [/][rgb(213,4,166)]t[/][rgb(210,3,170)]h[/][ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpectreMarkupSeed2 {
            get {
                return ResourceManager.GetString("SpectreMarkupSeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [rgb(254,68,60)][[/][rgb(254,64,64)]L[/][rgb(254,61,67)]e[/][rgb(254,57,71)]f[/][rgb(254,54,75)]t[/][rgb(253,50,79)][[/][rgb(253,47,83)][[/][rgb(252,44,87)]M[/][rgb(251,41,91)]i[/][rgb(250,38,95)]d[/][rgb(249,35,99)]d[/][rgb(248,32,103)]l[/][rgb(246,29,107)]e[/][rgb(245,26,111)]][/][rgb(243,24,116)]][/][rgb(241,22,120)]R[/][rgb(239,19,124)]i[/][rgb(237,17,128)]g[/][rgb(235,15,132)]h[/][rgb(233,13,137)]t[/][rgb(230,11,141)]][/].
        /// </summary>
        internal static string SpectreMarkupWithEscapeCharacters {
            get {
                return ResourceManager.GetString("SpectreMarkupWithEscapeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectreRainbow.
        /// </summary>
        internal static string SpectreText {
            get {
                return ResourceManager.GetString("SpectreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Left[[Middle]]Right].
        /// </summary>
        internal static string SpectreTextWithEscapeCharacters {
            get {
                return ResourceManager.GetString("SpectreTextWithEscapeCharacters", resourceCulture);
            }
        }
    }
}
